os: linux
dist: trusty
language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15

matrix:
  include:
    - arch: ppc64le
      addons: [ apt: [ packages: maven ]]
      jdk: oraclejdk8
    - arch: ppc64le
      addons: [ apt: [ packages: maven ]]
      jdk: oraclejdk9
    - arch: ppc64le
      addons: [ apt: [ packages: maven ]]
      jdk: oraclejdk11
    - arch: ppc64le
      addons: [ apt: [ packages: maven ]]
      jdk: openjdk8
    - arch: ppc64le
      addons: [ apt: [ packages: maven ]]
      jdk: openjdk9
    - arch: ppc64le
      addons: [ apt: [ packages: maven ]]
      jdk: openjdk10
    - arch: ppc64le
      addons: [ apt: [ packages: maven ]]
      jdk: openjdk11
    - arch: ppc64le
      addons: [ apt: [ packages: maven ]]
      jdk: openjdk12
    - arch: ppc64le
      addons: [ apt: [ packages: maven ]]
      jdk: openjdk13
    - arch: ppc64le
      addons: [ apt: [ packages: maven ]]
      jdk: openjdk14
    - arch: ppc64le
      addons: [ apt: [ packages: maven ]]
      jdk: openjdk15

cache:
  directories:
    - $HOME/.m2

install:
  - cd $TRAVIS_BUILD_DIR/jaxrs-api
  - if [[ "${TRAVIS_CPU_ARCH}" == "ppc64le" ]]; then mvn install -Pstaging -DskipTests=true -B -V; else mvn install -Pstaging -DskipTests=true -Dmaven.javadoc.skip=true -B -V; fi
  - cd $TRAVIS_BUILD_DIR/examples
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd $TRAVIS_BUILD_DIR/jaxrs-spec
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - cd $TRAVIS_BUILD_DIR/jaxrs-api
  - mvn verify -Pstaging -B
  - cd $TRAVIS_BUILD_DIR/examples
  - mvn verify -B
  - cd $TRAVIS_BUILD_DIR/jaxrs-spec
  - mvn verify -B
