os: linux
dist: trusty
language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15

arch:
  - amd64
  - ppc64le

cache:
  directories:
    - $HOME/.m2

install:
  - cd $TRAVIS_BUILD_DIR/jaxrs-api
  - mvn install -Pstaging -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd $TRAVIS_BUILD_DIR/examples
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd $TRAVIS_BUILD_DIR/jaxrs-spec
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - cd $TRAVIS_BUILD_DIR/jaxrs-api
  - mvn verify -Pstaging -B
  - cd $TRAVIS_BUILD_DIR/examples
  - mvn verify -B
  - cd $TRAVIS_BUILD_DIR/jaxrs-spec
  - mvn verify -B
